GET  http://localhost:3000/events


###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "teste",
    "description": "testando",
    "date": "2021-09-01T00:00:00.000Z",
    "price": 100
}

###
GET  http://localhost:3000/events/063b284e-f104-4185-944c-c27600e9524c

###
PATCH http://localhost:3000/events/063b284e-f104-4185-944c-c27600e9524c
Content-Type: application/json

{
    "name": "Rick and Morty kakaka",
    "description": "testando 123",
    "date": "2021-09-01T00:00:00.000Z",
    "price": 100
}

###
DELETE   http://localhost:3000/events/063b284e-f104-4185-944c-c27600e9524c